[versions]
agp = "8.8.2"
kotlin = "2.1.10"
coreKtx = "1.15.0"
espressoCore = "3.6.1"
appcompat = "1.7.0"
activity = "1.10.1"
material = "1.12.0"
constraintlayout = "2.2.0"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlinSafeArgs = "2.8.5"
googleServices = "4.4.2"
firebaseBom = "33.10.0"
firebaseStorage = "21.0.1"
navigation = "2.8.5"
koinVersion = "4.0.1"
gsonVersion = "2.10.1"
swipereVersion = "1.1.0"
splashScreen = "1.0.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "kotlinSafeArgs" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashScreen" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
swipere = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swipereVersion" }

#firebase
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-storage = { module = "com.google.firebase:firebase-storage", version.ref = "firebaseStorage" }

#navigation
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

# Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinVersion" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinVersion" }

# Gson
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gsonVersion" }